### ISSUE TITLE
update_hexagon fails to find setup

### ISSUE THREAD

**Issue by Lt-Mayonesa** [redbeestudios/hexagon#41]
> hexagon version: v0.14.0

Al ejecutar `hexagon` o una cli tira:
```
Traceback (most recent call last):
  File "/home/joaco/.local/bin/hexagon", line 8, in <module>
    sys.exit(main())
  File "/home/joaco/.local/lib/python3.8/site-packages/hexagon/__main__.py", line 26, in main
    check_for_hexagon_updates()
  File "/home/joaco/.local/lib/python3.8/site-packages/hexagon/support/update_hexagon.py", line 56, in check_for_hexagon_updates
    import setup  # noqa: F401
ModuleNotFoundError: No module named 'setup'
```

![image](https://user-images.githubusercontent.com/11464844/126402614-2cc376c8-fc4e-454e-aeec-a59740406d18.png)

**Comment by MarcoScabbiolo** [comment]
Uh que cagada, se ve que `setup.py` cuando se buildea desaparece.
